POST http://127.0.0.1:9999/users/
Accept: application/json
Content-Type: application/json


{
    "username": "test2",
    "password": "test",
    "role": "role"
}


POST http://127.0.0.1:9999/auth/
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "test"  
}